version: '3.3'
services:
    db:
        build: ./db
        container_name: bd-pre
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: 'senha'
            POSTGRES_DB: 'bd'
            POSTGRES_USER: 'postgres'
        networks: 
            - postgres-bd-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'email@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'senha'
        ports:
            - "80:80"
        depends_on:
            - db
        networks:
            - postgres-bd-network
networks:
    postgres-bd-network:
        driver: bridge

